# Minimum probability flow

In [1]:
import numpy as np
import theano.tensor as T

## Preparation
To get started we first have to prepare the data to work with. The steps to synthesis the data are as follows:
1. Form a $n \times n$ matrix $W$ that is symmetric with diagonal entries set to zeros.
2. The bias vector is $n \times 1$ that is either set to zero or takes binary inputs.
3. Initialise a vector of size $n$ that has binary entries, $x^{(1)}$, which is used to generate the subsequent sample values.
4. Given $x^{(i)}$, for each row $j$
\begin{align*}
p_{j}^{(i+1)} &= \sigma\left(\sum_{k=1}^{n}w_{jk}x_{k}^{(i)}\right)\\
%x_{j}^{(i+1)}&=\sigma(\tilde{x}_{j}^{(i+1)})
\end{align*}
where $\sigma$ is the sigmoid function, thus produces a row of values between 0 and 1. Each entry of $x_j^{(i+1)}$ is Bernoulli distributed with parameter $p_{j}^{(i+1)}$.
The requirement of being symmetric with diagonal entries set to zero for $W$ is necessary for the data to be 'good'. Shall elaborate on the good later.

In [11]:
# Set dimension of the data vector
n = 16

# Initialize weight matrix that is symmetric and has zero diagonal entries
W = np.triu(np.random.normal(0,1,(n,n)))*(1 - np.eye(n))
# W = np.triu(np.random.rand(n,n))*(1 - np.eye(n))
W = W + np.transpose(W)
# W = 2*W - 1

# Ask Gary if the initialization of the W matrix is between 0 and 1 as I will get a all ones dataset

# To test if W is symmetric
# print (W)
# print ((W == np.transpose(W)).all())

# Bias vector with binary inputs
#b = np.random.randint(2, size = n).reshape(n,-1)
b = np.zeros((1,n)).reshape(n,-1)

# Seed data vector to generate data
x = np.random.randint(2, size = n).reshape(n,-1)

print ('x:',np.transpose(x))
print ('W:',W)
print ('b:',np.transpose(b))

x: [[0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1]]
W: [[ 0.         -1.21919523  0.2127522   0.34840266  1.2110798  -0.57660002
  -0.24779665 -0.41759623 -1.95514855 -1.18355395  0.37768358  0.60076739
   0.04254987 -1.390525   -0.12530252 -1.3940747 ]
 [-1.21919523 -0.          0.95410619 -0.075351    0.83647272  0.27871444
   2.33428423 -1.64114003 -0.5548095   0.83205779  0.27827386  1.86128138
   0.21200463 -0.0830844  -0.46360497 -0.54160192]
 [ 0.2127522   0.95410619 -0.          1.20672068  0.3423558  -0.50456196
   0.54511542  1.29274506  0.04425316 -0.5101381   0.63031831 -1.00247859
   0.24728212  1.28784299  0.01431694  0.22516807]
 [ 0.34840266 -0.075351    1.20672068 -0.         -1.59145413 -0.62226857
   0.05573668  0.20629578  1.3411748   1.74843208  0.82859588  0.60849261
  -2.31954787 -0.02497317 -1.48583816 -1.54006291]
 [ 1.2110798   0.83647272  0.3423558  -1.59145413 -0.          1.00988891
   0.24252357 -0.01611485  0.85548308 -0.69838366 -1.66123154  0.37563742
   0.41026805 

In [12]:
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

In [13]:
def gendata(x, W, b):
#     print (W.dot(x) + b)
#     print (sigmoid(W.dot(x) + b))
    return np.random.binomial(1,sigmoid(W.dot(x)+b))    

To be done: while looping concantenate the data for every thousand.

In [18]:
for i in np.arange(100):
    x = gendata(x, W, b)
    print (np.transpose(x))

[[0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0]]
[[0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0]]
[[0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 0 1 1 0 1 1 1 0 0]]
[[0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0]]
[[0 1 0 0 1 1 1 1 1 1 0 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0]]
[[0 1 1 0 0 0 1 0 1 1 1 1 0 1 0 0]]
[[0 1 1 1 0 1 1 1 0 1 1 1 1 1 0 0]]
[[0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0]]
[[0 1 1 1 0 1 1 1 0 1 0 1 1 1 0 0]]
[[0 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0]]
[[0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0]]
[[0 1 1 1 0 0 1 0 0 1 0 1 1 1 0 0]]
[[0 1 1 0 1 0 1 0 1 1 1 1 0 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0]]
[[0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]]
[[0 1 1 1 1 1 1 1 1 1 1 1 1 