# Minimum probability flow

In [1]:
import numpy as np
import theano.tensor as T

## Preparation
To get started we first have to prepare the data to work with. The steps to synthesis the data are as follows:
1. Form a $n \times n$ matrix $W$ that is symmetric with diagonal entries set to zeros.
2. The bias vector is $n \times 1$ that is either set to zero or takes binary inputs.
3. Initialise a vector of size $n$ that has binary entries, $x^{(1)}$, which is used to generate the subsequent sample values.
4. Given $x^{(i)}$, for each row $j$
\begin{align*}
p_{j}^{(i+1)} &= \sigma\left(\sum_{k=1}^{n}w_{jk}x_{k}^{(i)}\right)\\
%x_{j}^{(i+1)}&=\sigma(\tilde{x}_{j}^{(i+1)})
\end{align*}
where $\sigma$ is the sigmoid function, thus produces a row of values between 0 and 1. Each entry of $x_j^{(i+1)}$ is Bernoulli distributed with parameter $p_{j}^{(i+1)}$.
The requirement of being symmetric with diagonal entries set to zero for $W$ is necessary for the data to be 'good'. Shall elaborate on the good later.

In [24]:
# Set dimension of the data vector
n = 16

# Initialize weight matrix that is symmetric and has zero diagonal entries
# W = np.triu(np.random.normal(0,1,(n,n)))*(1 - np.eye(n))
W = np.triu(np.random.rand(n,n))*(1 - np.eye(n))
W = W + np.transpose(W)
W = 2*W - 1

# Ask Gary if the initialization of the W matrix is between 0 and 1 as I will get a all ones dataset

# To test if W is symmetric
# print (W)
# print ((W == np.transpose(W)).all())

# Bias vector with binary inputs
#b = np.random.randint(2, size = n).reshape(n,-1)
b = np.zeros((1,n)).reshape(n,-1)

# Seed data vector to generate data
x = np.random.randint(2, size = n).reshape(n,-1)

print ('x:',np.transpose(x))
print ('W:',W)
print ('b:',np.transpose(b))

x: [[0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1]]
W: [[-1.         -0.20057741 -0.22754287 -0.9369603  -0.47774934  0.50280341
  -0.37380733  0.78123877  0.3809893  -0.26668995  0.85325307 -0.4895073
   0.69547324 -0.49539535 -0.87679366  0.40432358]
 [-0.20057741 -1.          0.78048164  0.52623245 -0.52984692 -0.68126731
  -0.64120093  0.49685403 -0.47903665  0.45250762  0.8363376  -0.30420229
  -0.61487372  0.14325792 -0.0550722  -0.51711991]
 [-0.22754287  0.78048164 -1.          0.87865492 -0.09607977 -0.75976239
   0.55648797 -0.12308346 -0.11070081  0.7867596  -0.67090432  0.18998381
  -0.29382396 -0.13419263  0.38168901 -0.8791516 ]
 [-0.9369603   0.52623245  0.87865492 -1.          0.7183934   0.51986674
   0.86704343 -0.10242716 -0.456637   -0.07977738 -0.93096476  0.77257717
  -0.12562157  0.5442011   0.66910027 -0.83263495]
 [-0.47774934 -0.52984692 -0.09607977  0.7183934  -1.         -0.61599136
  -0.57928156 -0.92097703  0.9067089  -0.74319476  0.43135643 -0.30418869
  -0.32526475  

In [25]:
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

In [28]:
def gendata(x, W, b):
#     print (W.dot(x) + b)
#     print (sigmoid(W.dot(x) + b))
    return np.random.binomial(1,sigmoid(W.dot(x)+b))    

In [29]:
for i in np.arange(10):
    x = gendata(x, W, b)
    print (np.transpose(x))

[[0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1]]
[[0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0]]
[[0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 1]]
[[0 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0]]
[[0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0]]
[[1 1 0 0 1 0 0 0 0 0 1 1 0 1 1 1]]
[[0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0]]
[[1 1 0 0 1 0 1 1 1 0 0 1 1 1 1 1]]
[[1 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1]]
[[1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0]]
